- name: Import variables
  ansible.builtin.include_vars: key.yml

- name: Create EC2 Key with Specific Key Material
  no_log: false
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
    key_material: "{{ key_material }}"
    state: "{{ ec2_key_state }}"
  when: 
    - key_material is defined
    - "ec2_key_state == 'present'"

- name: Create New EC2 Key
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
    state: "{{ ec2_key_state }}"
  when: 
    - key_material is not defined
    - "ec2_key_state == 'present'"
  register: ec2_key_material

- set_fact:
    new_ec2_key: ec2_key_material
  when: ec2_key_material is defined
