- name: Import variables
  ansible.builtin.include_vars: instance.yml

- name: Create New Instance
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_name }}"
    wait: "{{ wait }}"
    count: "{{ count }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    network:
      assign_public_ip: "{{ assign_public_ip }}"
    tags:
      "{{ instance_tags }}"
    state: "{{ ec2_instance_state }}"
  when: "ec2_instance_state == 'present'"
