- name: Create EC2 Key with Specific Key Material
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
    key_material: "{{ key_ssh-rsa }}"
    state: "{{ ec2_key_state }}"
  when: 
    - key_material is defined
    - "ec2_key_state == 'present'"

- name: Create New EC2 Key
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    region: "{{ region }}"
    state: "{{ ec2_key_state }}"
  when: 
    - key_material is not defined
    - "ec2_key_state == 'present'"
