- name: EC2 Instance Power Operation
  amazon.aws.ec2:
    instance_ids: "{{ instance_ids }}"
    state: "{{ ec2_instance_state }}"
  when: "ec2_instance_state != 'present' and ec2_instance_state != 'absent'"
