- name: Import variables
  ansible.builtin.include_vars: instance.yml

- name: Delete EC2 Instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ instance_ids }}"
    state: "{{ ec2_instance_state }}"
  when: "ec2_instance_state == 'absent'"
