- name: Import variables
  ansible.builtin.include_vars: key.yml

- name: Delete EC2 Key
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    state: "{{ ec2_key_state }}"
  when: "ec2_key_state == 'absent'"
